@startuml
!include ../style.puml

scale 0.8
package bwcp {
    interface Server FACADE_COLOR {
        void onConnection(AuthPacket)
        void onDisconnection(FinPacket)
        Optional<ComHistory> fetchComHistory(long startTime, long endTime, String username, String adminAor)
        FetchCallResponse fetchCallingInfoFromCallResource(String callResource, String userAor)
        boolean isSessionAlive(String aor)
        boolean isWired()
    }

    class BwcpServer FACADE_COLOR {
    }


    class EventController {
        ResponseEntity receive(String xmlContent)
    }

    package logic SERVICE_COLOR {
        package parser SERVICE_COLOR {
             interface AbstractParser SERVICE_COLOR {
                Optional tryParse(Document)
             }
             package events SERVICE_COLOR {
                class XYZEventParsers SERVICE_COLOR
             }

             package responses SERVICE_COLOR {
                 class XYZResponseParsers SERVICE_COLOR
             }
        }

        package services SERVICE_COLOR {
            class MonitorResourceService SERVICE_COLOR
            class SessionService SERVICE_COLOR
            class FetchComHistoryService SERVICE_COLOR
            class CallResourceService SERVICE_COLOR
            class EventService SERVICE_COLOR
        }

        package managers SERVICE_COLOR {
            class SessionManager SERVICE_COLOR {
                void createSession(AuthPacket)
                void deleteSession(FinPacket)
            }
        }

    }

    package models MODEL_COLOR {
        package _events_ MODEL_COLOR {
            interface Event MODEL_COLOR
            class XYZEvent MODEL_COLOR
        }
        package _responses_ MODEL_COLOR {
            interface Response MODEL_COLOR
            class XYZResponse MODEL_COLOR
        }
        class BwcpSession MODEL_COLOR {
            void start()
            void stop()
            void resume()
            void isAlive()
        }
    }

    package storage STORAGE_COLOR {
        interface ClientStorage STORAGE_COLOR {
            void addClient
            String getBlueWaveTokenByAor(aor)
            String getMonitorResourceByAor(aor)
            boolean containsClient(aor)
            void removeAllResourceByAor(aor)
        }
        class BwcpClientStorage STORAGE_COLOR
    }
    interface ClientAction FACADE_COLOR
}

EventController -down[hidden]-services

BwcpServer .up.|> Server
XYZEventParsers .up.|> AbstractParser
XYZResponseParsers .up.|> AbstractParser
XYZEvent .up.|> Event
XYZResponse .up.|> Response
BwcpSession .up.> SessionService
BwcpSession .up.> MonitorResourceService
BwcpSession .up.> ClientStorage
XYZEventParsers .down.> XYZEvent
XYZResponseParsers .down.> XYZResponse
BwcpClientStorage .up.|> ClientStorage
SessionManager ..> BwcpSession
BwcpServer ..> SessionManager
BwcpServer ..> FetchComHistoryService
BwcpServer ..> CallResourceService
EventService .up.> ClientAction
BwcpServer ..> ClientAction
EventController .up.> EventService

@enduml