@startuml

package bc-tech-backend{
  package ControlCenter{
    class ControlCenterController{
      void receiveLog(BcTecLog)
      void receiveParsedEvent(Event)
      void importLicense(xml)
    }

    class ControlCenterService{
      Map<String, BwcpSession> SessionPool
      Map<String, BwcpLicense> LicensePool
      SessionPoolService
      LicensePoolService

      onIncomingLineStatusEvent()
      onOriginatedEvent()
      onOutgoingOriginatedEvent()
      onReleaseEvent()
      onBargeEvent()
      onTransferEvent()
      generateResultMap()
      void sendToClient()
    }

    class SessionPoolService{
      BwcpSession createSession(String aor)
      BwcpSession refreshSession(String aor)
      boolean deleteSession(String aor)
    }

    class LicensePoolService{
      BwcpLicense fetchLicense(String aor)
      BwcpLicense refreshLicense(String aor)
      boolean deleteLicense(String aor)
    }

    class LogService{
      void sendLogToSmtp(BcTecLog)
      boolean checkLogFormat(BcTecLog)
    }
  }

  package Smtp{
    class SmtpController{
      void receiveLog(BcTecLog)
    }

    class SmtpService{
      void sendLog(BcTechLog)
      void recordLog(BcTechLog)
    }
  }

  package Backend{
    class AuthController{
      void login(String username, String password)
    }
    class AuthService{
      void verification(String username, String password)
    }
  }

  package Bwcp{
    class Bwcp{

    }
  }

  package commons{
    package model{
      class BcTecLog{

      }
      class BwcpSession{

      }
      class BwcpLicense{

      }
    }
  }
}

ControlCenterController --> ControlCenterService
ControlCenterService --> SessionPoolService
ControlCenterService --> LicensePoolService
ControlCenterController --> LogService
SmtpController --> SmtpService
AuthController --> AuthService

LogService .. SmtpController
AuthService .. ControlCenterController
SessionPoolService .. Bwcp

@enduml