@startuml
!include ../style.puml

scale 0.8
package controller {
  class UserController {}
}

package bwcp {
  package logic.services SERVICE_COLOR {
    class BasicService SERVICE_COLOR {}
  }
}

package logic.service SERVICE_COLOR {
  class UserService SERVICE_COLOR {}
  class ConfigService SERVICE_COLOR {}
}

package repository {
  class UserRepository {}
  class UserAuthRepository {}
}

package commons {
  package service.report SERVICE_COLOR {
    class ReportService SERVICE_COLOR {}
  }
}

UserController ..> BasicService
UserController ..> UserService

BasicService ..> ConfigService

UserService ..> UserRepository
UserService ..> UserAuthRepository
UserService ..> ReportService

@enduml