@startuml

package log {
  class Log {
    String relatedFunction,
    String description,
    String severityType,
    String exceptionType,
    String uri,
    String detailDescription,
    Instant time,

    Log()
    constructLog()
    toReport()
    formatTime()
  }
  class ExceptionType {
    
  }
  class RelatedFunction {

  }
  class SeverityType {

  }
}

@enduml